# Generated by Django 4.1.2 on 2022-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('ocorrencia', models.CharField(max_length=255)),
                ('gravidade', models.IntegerField()),
            ],
        ),
    ]
