# Generated by Django 4.1.2 on 2022-10-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='CPF',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='gravidade',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='local',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ocorrencia',
            field=models.CharField(max_length=255),
        ),
    ]
